### ISSUE TITLE
LVB timestamps granularity is too course

### ISSUE THREAD

**Issue by daniel-thompson** [Seagate/propeller#131]
Currently LVBs contains a 64-bit timestamp in a calendar form (yyyy-mm-dd HH:MM:SS) that is used to determine whether a node should refresh its metadata cache.

There appears to be a risk of timestamp collisions due to the course granularity of this timestamp. Collisions could occur in several ways but a simple example is a updating the physical volumes within a volume group.

As a concrete example consider a VG containing 3 PVs where an operator removes two PVs and then adds two more using a management script (two independent processes are used to deploy the combined update). It is highly likely that both processes will complete in the same second hence the second update has a colliding timestamp. If another node observed the *first* update and refresh its cache then this would result in a safety problem due to that node operating with a reduce majority threshold because it is unaware of the second update.

**Comment by daniel-thompson** [comment]
Should we close this now?

**Comment by Leo-Yan** [comment]
Yes, let's close this ticket.
