### ISSUE TITLE
Add "official" version number and make a not-a-demo release

### ISSUE THREAD

**Issue by daniel-thompson** [Seagate/propeller#137]
Changes requests:

1. Add version information as a variable in the makefile (to be updated each release) and connect this up to preprocessor symbols ;-)
2. Allow `git describe` to override the version information if (and only if) we detect we are building from a git repo
3. Add --version CLI flag to extract version information
4. Log version info to syslog

**Comment by daniel-thompson** [comment]
5. Make 0.9 release.

**Comment by Leo-Yan** [comment]
PR https://github.com/Seagate/propeller/pull/139 has been uploaded for support version number.
